[toolchain]
channel = "nightly"
components = [
  "rust-src"
]

[build]
target = [
  "triplet/x86_64-unknown-kernel.json",
#  "triplet/aarch64-unknown-kernel.json",
#  "triplet/riscv64-unknown-kernel.json",
]

[unstable]
bindeps = true
build-std = [
  "alloc",
  "core",
  "compiler_builtins"
]
build-std-features = [
  "compiler-builtins-mem"
]

#[target.'cfg(target_os = "none")']
#runner = "bootimage runner"
